theme: minima
minima:
  skin: dark
  av:
    - title: "Home"
      url: /
    - title: "About"
      url: /about/
    - title: "Install"
      url: /docs/install/
    - title: "Documentation"
      url: /docs/
    - title: "Guide Book"
      url: /book/
